export const messages = {
  en: {
    apiChecked:'API checked', staleView:'Earlier observations may still be shown; they have not been refreshed.', features:'Host features', enabled:'Enabled', allowedReads:'Allowed reads', requestedPermissions:'Requested permissions', title:'Gateway dashboard', subtitle:'Read-only management', overview:'Overview', runtime:'Runtime', configuration:'Configuration', extensions:'Extensions', usage:'Usage', activity:'Activity',
    connect:'Open dashboard', readToken:'Read credential', target:'Target ID', loginNote:'Use the dedicated read credential provided by your host.', loginBoundary:'Management credentials cannot be used for a browser session.', readOnly:'Read only', signOut:'Sign out', refresh:'Refresh', refreshing:'Refreshing…', lastObserved:'Observed', noObservation:'Not observed', unsupported:'Not provided by this host', unavailable:'Not available', observed:'Observed', unsafe_numeric_value:'This browser cannot preserve the numeric precision of this response.', connected:'Connected', waiting:'Waiting for API',
    running:'Running', stopped:'Stopped', unowned:'Not owned', pending:'Pending application', selected:'Selected for next start', effective:'In effective configuration', installed:'Installed', verified:'Verified', invalid:'Verification failed', yes:'Yes', no:'No', unknown:'Unknown',
    instance:'Instance', configurationDigest:'Configuration digest', executionDigest:'Execution digest', desired:'Selected configuration', current:'Effective configuration', candidates:'Saved candidates', needsRestart:'Selection will apply on an explicit start or restart.', externalChange:'State differs from the current controller’s last confirmed observation.', noRuntime:'No runtime observation is available.',
    package:'Package', version:'Version', permissions:'Permissions', packageDigest:'Package digest', noPackages:'No installed packages were reported.', packageNote:'Installation, next-start selection and effective configuration are separate states. Codecs run per request.', readOnlyPackages:'Installation, removal and activation controls are not part of this view.',
    days:'days', calls:'Attempts', final:'Final observations', partial:'Partial', unobserved:'Unobserved', unfinished:'Unfinished', model:'Model', provider:'Provider', date:'Date', input:'Input tokens', output:'Output tokens', reasoning:'Reasoning tokens', noUsage:'No usage groups were reported for this interval.', usageNote:'Missing counters stay unknown. HTTP responses and transport completion do not prove model completion.',
    action:'Action', subject:'Subject', state:'State', operation:'Operation', recordedState:'Recorded state', observedState:'Observed state', event:'Event', more:'Load more', noOperations:'No management operations were reported.', details:'Details', close:'Close', queued:'Queued', succeeded:'Succeeded', failed:'Failed', uncertain:'Uncertain', accepted:'Accepted', started:'Started', finished:'Finished', recovery:'Recovery', reconciled:'Reconciled', system:'System observation',
    noData:'No observation is available for this view.', metadata:'Module metadata', capabilityNote:'Features and available actions are provided by the host. This dashboard only reads them.', operationNote:'An admitted operation ID is not proof that its effect completed.',
    error:'The management API could not provide this view.', unauthorized:'Your read session is missing, expired or no longer authorized.', forbidden:'This read credential does not allow the requested view.', read_credential_required:'Use a dedicated read credential, not a management credential.', invalid_read_credential:'Enter a valid read credential.', invalid_target:'Enter a valid registered target ID.', connection_unavailable:'The management API is unavailable. Check that the host is running.', unsupported_contract:'This API contract is not supported by this dashboard.', unsupported_operation:'This host does not provide the requested view.', host_rejected:'The API host does not match the configured loopback address.', origin_rejected:'The API rejected this browser origin.', result_record_missing:'The worker ended without a confirmed result record. Reconciliation is required.',
  },
  ko: {
    apiChecked:'API 확인 시각', staleView:'이전 관측이 남아 있을 수 있으며 새로 확인된 값이 아닙니다.', features:'호스트 기능', enabled:'활성화됨', allowedReads:'허용된 조회', requestedPermissions:'요청 권한', title:'Gateway 대시보드', subtitle:'조회 전용 관리', overview:'개요', runtime:'실행 상태', configuration:'구성', extensions:'확장', usage:'사용량', activity:'작업 이력',
    connect:'대시보드 열기', readToken:'조회 credential', target:'대상 ID', loginNote:'호스트에서 제공한 전용 조회 credential을 사용하세요.', loginBoundary:'변경용 관리 credential로는 브라우저 세션을 만들 수 없습니다.', readOnly:'조회 전용', signOut:'로그아웃', refresh:'새로고침', refreshing:'조회 중…', lastObserved:'관측 시각', noObservation:'미관측', unsupported:'호스트 미제공', unavailable:'조회 불가', observed:'관측됨', unsafe_numeric_value:'이 브라우저에서 응답의 숫자 정밀도를 보존할 수 없습니다.', connected:'연결됨', waiting:'API 연결 대기',
    running:'실행 중', stopped:'중지됨', unowned:'소유하지 않음', pending:'적용 대기', selected:'다음 시작에 선택됨', effective:'실제 실행 구성에 포함', installed:'설치됨', verified:'검증됨', invalid:'검증 실패', yes:'예', no:'아니요', unknown:'알 수 없음',
    instance:'실행 인스턴스', configurationDigest:'구성 digest', executionDigest:'실행 digest', desired:'선택된 구성', current:'실제 실행 구성', candidates:'저장된 후보', needsRestart:'명시적으로 시작하거나 재시작할 때 선택을 적용합니다.', externalChange:'현재 controller가 마지막으로 확인한 관측과 상태가 다릅니다.', noRuntime:'실행 상태를 아직 관측하지 못했습니다.',
    package:'패키지', version:'버전', permissions:'권한', packageDigest:'패키지 digest', noPackages:'설치된 패키지가 보고되지 않았습니다.', packageNote:'설치·다음 시작 선택·실제 실행 구성은 서로 다른 상태입니다. Codec은 요청별로 실행됩니다.', readOnlyPackages:'이 화면에는 설치·제거·활성화 제어가 없습니다.',
    days:'일', calls:'호출 시도', final:'최종 관측', partial:'부분 관측', unobserved:'미관측', unfinished:'미완결', model:'모델', provider:'Provider', date:'날짜', input:'입력 토큰', output:'출력 토큰', reasoning:'추론 토큰', noUsage:'이 기간에 보고된 사용량 그룹이 없습니다.', usageNote:'누락된 카운터는 알 수 없는 상태로 유지합니다. HTTP 응답이나 전송 종료는 모델 완료의 증거가 아닙니다.',
    action:'작업', subject:'주체', state:'상태', operation:'작업 ID', recordedState:'기록 상태', observedState:'관측 상태', event:'이벤트', more:'더 보기', noOperations:'보고된 관리 작업이 없습니다.', details:'자세히', close:'닫기', queued:'대기', succeeded:'성공', failed:'실패', uncertain:'미확정', accepted:'시작 의도 기록', started:'실행 시작', finished:'결과 기록', recovery:'복구 관측', reconciled:'상태 조정', system:'시스템 관측',
    noData:'이 화면에서 확인할 수 있는 관측이 없습니다.', metadata:'Module 정보', capabilityNote:'호스트가 기능과 허용 작업을 제공합니다. 이 대시보드는 해당 정보를 조회합니다.', operationNote:'작업 ID가 발급되어도 실제 변경의 완료를 의미하지 않습니다.',
    error:'관리 API가 이 화면의 정보를 제공하지 못했습니다.', unauthorized:'조회 세션이 없거나 만료되었거나 권한이 변경되었습니다.', forbidden:'이 조회 credential에는 해당 화면의 권한이 없습니다.', read_credential_required:'관리 credential 대신 전용 조회 credential을 사용하세요.', invalid_read_credential:'유효한 조회 credential을 입력하세요.', invalid_target:'등록된 대상 ID를 입력하세요.', connection_unavailable:'관리 API에 연결할 수 없습니다. 호스트가 실행 중인지 확인하세요.', unsupported_contract:'이 대시보드가 지원하지 않는 API 계약입니다.', unsupported_operation:'호스트가 해당 조회를 제공하지 않습니다.', host_rejected:'API 호스트가 설정된 loopback 주소와 다릅니다.', origin_rejected:'API가 이 브라우저 Origin을 거절했습니다.', result_record_missing:'Worker가 결과 기록을 확인하지 못한 채 종료되었습니다. 상태 조정이 필요합니다.',
  },
};
